[package]
name    = "ulid"
description = "PostgreSQL extension for ULID"
publish = false
version = "0.1.0"

edition      = "2021"
rust-version = "1.68.0"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg15"]
pg11    = ["pgx-tests/pg11", "pgx/pg11"]
pg12    = ["pgx-tests/pg12", "pgx/pg12"]
pg13    = ["pgx-tests/pg13", "pgx/pg13"]
pg14    = ["pgx-tests/pg14", "pgx/pg14"]
pg15    = ["pgx-tests/pg15", "pgx/pg15"]
pg_test = []

[dependencies]
inner_ulid = { package = "ulid", version = "1.0.0" }
pgx        = "=0.7.3"

[dev-dependencies]
pgx-tests = "=0.7.3"

[profile.dev]
panic = "unwind"

[profile.release]
codegen-units = 1
lto           = "fat"
opt-level     = 3
panic         = "unwind"
